baseURL = "https://olasergiolas.github.io"
# title = "sergi0"
author = "Sergio García"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "sergi0's blog"

[params]
  color = 'linen'

  twitter = 'sergiogc_5'
  github = 'Olasergiolas'

  avatar = 'https://avatars.githubusercontent.com/u/32015541?s=400&u=17235ce4b8ce62c3f061c38cdbaeb7157bc0bc7a&v=4'
  name = 'Sergio García'
  bio = 'Reversing stuff for fun'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true